### ISSUE TITLE
can xxhash-c-sys invoke shared object instead of statically-linked code?

### ISSUE THREAD

**Issue by dkg** [DoumanAsh/xxhash-c-sys#1]
on debian, we have libxxhash available in the operating system.

I'd like to ship xxhash-c-sys such that it runs against the local shared object, rather than statically compiling and shipping a `.a` file.

I can hack at the module to get it to do that, but if you're up for adopting those changes upstream, or if you have a preference for how to do that, i'd be happy to use an upstream-approved way to do it.

**Comment by DoumanAsh** [comment]
@dkg the problem with shared library approach is that it is difficult guarantee correct hash output across different systems
The reason I prefer static linking here is that xxhash output is not stable across versions (at least xxh3 as it is new algorithm) hence xxhash source code is copied inside this crate.

But if you can make build script that can target particular version of xxhash I'm ok with it.
Note that current version of bindings are generated for `0.8.1` so they are invalid for any other version (even 0.8.0 because 0.8.1 expanded API so there can be link issues if you use these new functions)

**Comment by dkg** [comment]
> the problem with shared library approach is that it is difficult guarantee correct hash output across different systems

Can you explain why this is difficult?  i mean, the C library's header `xxhash.h` is a long howl of nightmarish cleverness.  But the library still exposes a specific, actionable API with function entry points that appear to match `lib/bindings.rs`.  What makes it more troubling than any other C function?

I do understand the concern about version skew, and would be completely fine with tying this to a particular version of an external libxxhash library.

**Comment by DoumanAsh** [comment]
@dkg 
Well, to put it simply there are two main issues.
1. Hash output correctness - It is stable only across minor versions so any version within `0.8.x` are fine, but `0.y.x` changes are bad because xxh3 output is different on 0.7.x comparing to 0.8.x
2. API correctness. Bidnings (at least in current crate) were generated for 0.8.1. While it is backward compatible with 0.8.0, it does introduce new API functions and changes existing API. https://github.com/Cyan4973/xxHash/blob/dev/CHANGELOG#L6-L7= so this crate would work only if you do not rely on these API changes. This is minor concern because Rust is not going to expect new functions unless you explicitly invoke it, but it does mean that any code relying on these functions would not work with 0.8.0

I personally do not really care myself as I use this library for test, but I do not know if anyone else uses this library so if you want to make it use existing dynamic library you should at least guarantee build.rs do not go beyond minor version of this crate  0.8.x

**Comment by dkg** [comment]
OK, i think i understand the scope of what's necessary, and i just pushed a [patched version of `xxhash-c-sys`](https://salsa.debian.org/rust-team/debcargo-conf/-/tree/master/src/xxhash-c-sys/debian) into debian that uses the `pkg-config` crate and a versioned dependency on system `libxxhash` 0.8.1,  instead of compiling the C code locally.

If/when that makes it through debian's NEW queue, we should be able to get some test results from the [debian continuous integration](https://ci.debian.org) as well.

Thanks for bearing with me on this.

**Comment by DoumanAsh** [comment]
Sure, I assume you're fine with having it patched in debian?

**Comment by dkg** [comment]
yep, i don't mind maintaining the static→dynamic linking patch it in debian as long as you're ok with it.

The debian infrastructure for rust maintenance is a bit tricky, but the patch i landed on is ultimately not too complicated.

It's possible that this approach will turn up different results than the results you're seeing with your own test suites, of course.  If that happens, i hope you'll be ok with me asking for help figuring it out!

If you'd like to explore how we can reduce the patch in debian, i'd be game to talk it over with you, but i don't see a particularly straightforward way to do that.  The biggest part of the patch by far is just not-redistributing the embedded C library.  Then again, my not seeing a way to do something doesn't mean it doesn't exist.  i'd be happy to talk it over if you've got suggestions.

**Comment by DoumanAsh** [comment]
I'm not familar with `pkg-config` crate but as long as `atleast_version` guarantees semver compatibility (i.e. from `0.8.1` but not `0.9.x`) then it should be ifne
So I don't see much issue, let's leave this crate as it is

**Comment by dkg** [comment]
sounds good to me, thanks!

The `atleast_version` only sets a minimum bound; it doesn't explicitly respect semver in the way you describe.  But the C library ABI itself demands backward-incompatible changes to bump the SONAME, which means that the dynamic linking will fail clearly and explicitly.  Otherwise, anyone building a tool against libxxhash-dev today but linking against a future version would have serious breakage -- not just this crate.

So right now, the `libxxhash` shared object ships with SONAME 0, (the shared object is found by name `libxxhash.so.0` and the debian package is `libxxhash0`), and if the next revision of libxxhash actually breaks backward compat, the SONAME needs to be increased (the shared object is found by the name `libxxhash.so.1` and the package renamed to `libxxhash1` if the new SONAME is 1).

So as long as the SONAME is maintained properly in the `libxxhash` upstream -- they need to bump it whenever they make a semver-breaking change --  we have a mechanism that will keep this from being a problem for this crate.
